---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Kibana log folder is created
  ansible.builtin.file:
    path: "{{ kibana_log_path }}"
    mode: 0750
    state: directory
    owner: kibana
    group: root
  when: kibana_log_path is defined and kibana_log_path | length > 0

- name: Ensure Kibana cache permissions are correct
  ansible.builtin.file:
    path: /usr/share/kibana/optimize
    mode: 0775
    state: directory
    owner: kibana
    group: root
    recurse: yes

- name: Ensure Kibana is started and enabled at boot.
  ansible.builtin.service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  ansible.builtin.template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
